language: java
sudo: false

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk11
    - os: linux
      arch: s390x
      jdk: openjdk8
    - os: linux
      arch: s390x
      jdk: openjdk11


cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev
    - maven

script: mvn clean apache-rat:check install -DskipTests spotbugs:check checkstyle:check -Pfull-build

branches:
  only:
  - s390x-travis
